name: community_help
description: Aplicación móvil de ayuda comunitaria
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0
  flutter_dotenv: ^5.0.2
  provider: ^6.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  jwt_decoder: ^2.0.1
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  geolocator: ^14.0.1
  json_annotation: ^4.8.1
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env